name: Repo Security Scan
description: >
  Composite Action que roda Hadolint, Trivy, Docker Scout,
  tfsec, Checkov e Trivy-config; abre issues para cada finding.

inputs:
  docker-context:
    description: 'Diretório usado no docker build'
    default: '.'
    required: false

runs:
  using: composite
  steps:
    - name: Install scanners
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update -y
        sudo apt-get install -y jq curl git
        
        # Hadolint
        curl -L https://github.com/hadolint/hadolint/releases/latest/download/hadolint-$(uname -s)-$(uname -m) \
          -o /usr/local/bin/hadolint && chmod +x /usr/local/bin/hadolint
        
        # Trivy (cli + db embutido)
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
        
        # Terrascan
        curl -L "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Darwin_x86_64.tar.gz")" > terrascan.tar.gz
        tar -xf terrascan.tar.gz terrascan && rm terrascan.tar.gz
        install terrascan /usr/local/bin && rm terrascan

        # TFLint
        TFLINT_VERSION=$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | jq -r .tag_name)
        curl -sL "https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VERSION}/tflint_linux_amd64.zip" \
          -o tflint.zip
        unzip -q tflint.zip -d /usr/local/bin && chmod +x /usr/local/bin/tflint

        # Docker Scout
        docker scout --help > /dev/null 2>&1 || docker extension install docker/scout-cli:latest

    - name: Scan Docker and open issues
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        BUILD_CONTEXT:  ${{ inputs.docker-context }}
      run: |
        bash "${{ github.action_path }}/scripts/scan_docker.sh"

    - name: Scan Terraform and open issues
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        bash "${{ github.action_path }}/scripts/scan_terraform.sh"

    - name: Fail if any issues or problems were found
      shell: bash
      run: |
        if [ -f "$GITHUB_WORKSPACE/issues_found.flag" ] || \
          [ -f "$GITHUB_WORKSPACE/problems_found.flag" ]; then
          echo "Vulnerabilidades encontradas — falhando job"
          exit 1
        else
          echo "Nenhum problema pendente"
        fi
